### ISSUE TITLE
NPE with o8.flf font

### ISSUE THREAD

**Issue by greenlaw110** [lalyos/jfiglet#13]
Print `ABCDE` using [o8 font](http://www.figlet.org/fonts/o8.flf) gives me `NullPointerException`:

![image](https://cloud.githubusercontent.com/assets/216930/23098125/639c0c34-f69a-11e6-941c-16a4b94d67ea.png)

**Comment by mcwarman** [comment]
Looks like the [code here](https://github.com/lalyos/jfiglet/blob/master/src/main/java/com/github/lalyos/jfiglet/FigletFont.java#L119-L135) is causing the issue.

When the code gets to `888 888$@` in the file it treats it as char 888, then throwing out the assignments of everything else.

After reviewing the section [REQUIRED FIGCHARACTERS](https://github.com/lalyos/jfiglet/blob/master/figfont.txt#L1010) in figfont.txt it looks like the logic should be characters 32-126 then 196, 214, 220, 228, 246, 252, and 223. Then parse special chars.

I'll work on PR if that's OK?
