### ISSUE TITLE
Horizontal spacing increased 0.7 -> 0.8

### ISSUE THREAD

**Issue by davidmoten** [lalyos/jfiglet#21]
I ran the code fragment below and get quite different results between 0.7 and 0.8. I prefer 0.7 results. Was this change intended?

```java
FigletFont.convertOneLine(
                    cls.getResourceAsStream("/flf/cybermedium.flf"), "amsa-util");
```
0.7:
```
____ _  _ ____ ____   _  _ ___ _ _    
|__| |\/| [__  |__|   |  |  |  | |    
|  | |  | ___] |  |   |__|  |  | |___ 
```
 0.8:
```
 ____  _  _  ____  ____     _  _  ___  _  _    
 |__|  |\/|  [__   |__|     |  |   |   |  |    
 |  |  |  |  ___]  |  |     |__|   |   |  |___ 
```
cc @philipgroom @superevensteven

**Comment by mcwarman** [comment]
This looks like its related to the fix in #10 (which fixed #8 and #9).

The latest code (which is unreleased) fixes this as it now supports horizontal smushing #20:

```
System.out.println(FigletFont.convertOneLine("http://www.figlet.org/fonts/cybermedium.flf", "amsa-util"));
```

Produces the following:

```
____ _  _ ____ ____    _  _ ___ _ _    
|__| |\/| [__  |__| __ |  |  |  | |    
|  | |  | ___] |  |    |__|  |  | |___ 
                                       
```

The fix for this would be using 0.0.9 when it's released, that falls on @lalyos shoulders.

**Comment by davidmoten** [comment]
Thanks @mcwarman. A new release would be great @lalyos. (cc @superevensteven @philipgroom)

**Comment by davidmoten** [comment]
Can we get a new release?
